name: android_build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Get project URL
        id: get-project
        run: echo "PROJECT=$(cat project-to-build)" >> $GITHUB_OUTPUT

      - name: Clone target project
        run: git clone --depth=1 ${{ steps.get-project.outputs.PROJECT }} project

      - name: Build the app
        working-directory: ./project
        run: |
          if [ ! -f gradlew ]; then gradle wrapper; fi
          chmod +x gradlew
          ./gradlew assembleDebug --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: cherry-studio-apk
          path: project/app/build/outputs/apk/debug/*.apk
